import { LineCardData, SystemOverviewData } from '@/types/line';

export const INITIAL_LINES: LineCardData[] = [
  {
    id: '2cf',
    code: '2CF',
    name: 'SPINDLE 2CF',
    area: 'ASSY',
    metricLabel: 'OUTPUT RATE:',
    value: '92.4%',
    change: '-2.26%',
    subMetricLabel: 'BALANCE:',
    subMetricValue: '-250',
    status: 'RED',
    order: 1,
  },
  {
    id: 'assyarmc',
    code: 'ASSYARMC',
    name: 'Assy Arm Cushion',
    area: 'ASSY',
    metricLabel: 'OUTPUT RATE:',
    value: '97.5%',
    change: '0%',
    subMetricLabel: 'BALANCE:',
    subMetricValue: '0',
    status: 'YELLOW',
    order: 2,
  },
  {
    id: 'assysj',
    code: 'ASSYSJ',
    name: 'Assy Screw Jack',
    area: 'ASSY',
    metricLabel: 'OUTPUT RATE:',
    value: '96.9%',
    change: '0%',
    subMetricLabel: 'BALANCE:',
    subMetricValue: '0',
    status: 'YELLOW',
    order: 3,
  },
  {
    id: 'assystema',
    code: 'ASSYSTEMA',
    name: 'Assy Stem Manual',
    area: 'ASSY',
    metricLabel: 'OUTPUT RATE:',
    value: '88.5%',
    change: '-2.65%',
    subMetricLabel: 'BALANCE:',
    subMetricValue: '-15',
    status: 'RED',
    order: 4,
  },
  {
    id: 'assystemb',
    code: 'ASSYSTEMB',
    name: 'Assy Stem Auto',
    area: 'ASSY',
    metricLabel: 'OUTPUT RATE:',
    value: '102.3%',
    change: '+1.5%',
    subMetricLabel: 'BALANCE:',
    subMetricValue: '+45',
    status: 'GREEN',
    order: 5,
  },
  {
    id: 'brc',
    code: 'BRC',
    name: 'Ball Race',
    area: 'MACHINING',
    metricLabel: 'OUTPUT RATE:',
    value: '84.2%',
    change: '-3.68%',
    subMetricLabel: 'BALANCE:',
    subMetricValue: '-35',
    status: 'RED',
    order: 6,
  },
  {
    id: 'crc',
    code: 'CRC',
    name: 'Cone race',
    area: 'MACHINING',
    metricLabel: 'OUTPUT RATE:',
    value: '95.8%',
    change: '0%',
    subMetricLabel: 'BALANCE:',
    subMetricValue: '0',
    status: 'YELLOW',
    order: 7,
  },
  {
    id: 'd14',
    code: 'D14',
    name: 'HF D14N',
    area: 'MACHINING',
    metricLabel: 'OUTPUT RATE:',
    value: '98.1%',
    change: '0%',
    subMetricLabel: 'BALANCE:',
    subMetricValue: '0',
    status: 'YELLOW',
    order: 8,
  },
  {
    id: 'd34',
    code: 'D34',
    name: 'HF D34T',
    area: 'MACHINING',
    metricLabel: 'OUTPUT RATE:',
    value: '79.5%',
    change: '-0.69%',
    subMetricLabel: 'BALANCE:',
    subMetricValue: '-100',
    status: 'RED',
    order: 9,
  },
  {
    id: 'd80',
    code: 'D80',
    name: 'HF D80N',
    area: 'MACHINING',
    metricLabel: 'OUTPUT RATE:',
    value: '104.2%',
    change: '+0.47%',
    subMetricLabel: 'BALANCE:',
    subMetricValue: '+80',
    status: 'GREEN',
    order: 10,
  },
  {
    id: 'export',
    code: 'EXPORT',
    name: 'PAMA  EXPORT',
    area: 'ASSY',
    metricLabel: 'OUTPUT RATE:',
    value: '86.2%',
    change: '-1.89%',
    subMetricLabel: 'BALANCE:',
    subMetricValue: '-6',
    status: 'RED',
    order: 11,
  },
  {
    id: 'f1',
    code: 'F1',
    name: 'FORING 1',
    area: 'ASSY',
    metricLabel: 'OUTPUT RATE:',
    value: '89.0%',
    change: '-1.1%',
    subMetricLabel: 'BALANCE:',
    subMetricValue: '-22',
    status: 'RED',
    order: 12,
  },
  {
    id: 'f10',
    code: 'F10',
    name: 'FORGING 10',
    area: 'ASSY',
    metricLabel: 'OUTPUT RATE:',
    value: '94.5%',
    change: '0%',
    subMetricLabel: 'BALANCE:',
    subMetricValue: '0',
    status: 'YELLOW',
    order: 13,
  },
  {
    id: 'f11',
    code: 'F11',
    name: 'FORGING 11',
    area: 'ASSY',
    metricLabel: 'OUTPUT RATE:',
    value: '101.8%',
    change: '+0.2%',
    subMetricLabel: 'BALANCE:',
    subMetricValue: '+15',
    status: 'GREEN',
    order: 14,
  },
  {
    id: 'f4',
    code: 'F4',
    name: 'FORGING 4',
    area: 'FORGING',
    metricLabel: 'OUTPUT RATE:',
    value: '82.0%',
    change: '-1.45%',
    subMetricLabel: 'BALANCE:',
    subMetricValue: '-45',
    status: 'RED',
    order: 15,
  },
  {
    id: 'f5',
    code: 'F5',
    name: 'FORGING 5',
    area: 'ASSY',
    metricLabel: 'OUTPUT RATE:',
    value: '98.8%',
    change: '0%',
    subMetricLabel: 'BALANCE:',
    subMetricValue: '0',
    status: 'YELLOW',
    order: 16,
  },
  {
    id: 'f6',
    code: 'F6',
    name: 'FORGING 6',
    area: 'ASSY',
    metricLabel: 'OUTPUT RATE:',
    value: '84.0%',
    change: '-2.10%',
    subMetricLabel: 'BALANCE:',
    subMetricValue: '-12',
    status: 'RED',
    order: 17,
  },
  {
    id: 'f7',
    code: 'F7',
    name: 'FORGING 7',
    area: 'ASSY',
    metricLabel: 'OUTPUT RATE:',
    value: '103.4%',
    change: '+0.5%',
    subMetricLabel: 'BALANCE:',
    subMetricValue: '+30',
    status: 'GREEN',
    order: 18,
  },
  {
    id: 'f8',
    code: 'F8',
    name: 'FORGING 8',
    area: 'ASSY',
    metricLabel: 'OUTPUT RATE:',
    value: '93.0%',
    change: '0%',
    subMetricLabel: 'BALANCE:',
    subMetricValue: '0',
    status: 'YELLOW',
    order: 19,
  },
  {
    id: 'f9',
    code: 'F9',
    name: 'FORGING 9',
    area: 'ASSY',
    metricLabel: 'OUTPUT RATE:',
    value: '81.0%',
    change: '-3.20%',
    subMetricLabel: 'BALANCE:',
    subMetricValue: '-60',
    status: 'RED',
    order: 20,
  },
  {
    id: 'fg1',
    code: 'FG1',
    name: 'PJ FG 1',
    area: 'ASSY',
    metricLabel: 'OUTPUT RATE:',
    value: '105.1%',
    change: '+1.2%',
    subMetricLabel: 'BALANCE:',
    subMetricValue: '+50',
    status: 'GREEN',
    order: 21,
  },
  {
    id: 'fg2',
    code: 'FG2',
    name: 'PJ FG 2',
    area: 'ASSY',
    metricLabel: 'OUTPUT RATE:',
    value: '95.0%',
    change: '0%',
    subMetricLabel: 'BALANCE:',
    subMetricValue: '0',
    status: 'YELLOW',
    order: 22,
  },
  {
    id: 'hpm',
    code: 'HPM',
    name: 'HF HPM',
    area: 'MACHINING',
    metricLabel: 'OUTPUT RATE:',
    value: '78.2%',
    change: '-1.80%',
    subMetricLabel: 'BALANCE:',
    subMetricValue: '-85',
    status: 'RED',
    order: 23,
  },
  {
    id: 'lbj',
    code: 'LBJ',
    name: 'LOWER BALL JOINT',
    area: 'ASSY',
    metricLabel: 'OUTPUT RATE:',
    value: '83.0%',
    change: '-0.95%',
    subMetricLabel: 'BALANCE:',
    subMetricValue: '-32',
    status: 'RED',
    order: 24,
  },
  {
    id: 'msch',
    code: 'MSCH',
    name: 'MACHINING SHAFT',
    area: 'ASSY',
    metricLabel: 'OUTPUT RATE:',
    value: '96.0%',
    change: '0%',
    subMetricLabel: 'BALANCE:',
    subMetricValue: '0',
    status: 'YELLOW',
    order: 25,
  },
  {
    id: 'rt1',
    code: 'RT1',
    name: 'ROTOR-1',
    area: 'MACHINING',
    metricLabel: 'OUTPUT RATE:',
    value: '102.8%',
    change: '+0.3%',
    subMetricLabel: 'BALANCE:',
    subMetricValue: '+20',
    status: 'GREEN',
    order: 26,
  },
  {
    id: 'rt2',
    code: 'RT2',
    name: 'ROTOR-2',
    area: 'MACHINING',
    metricLabel: 'OUTPUT RATE:',
    value: '78.0%',
    change: '-2.40%',
    subMetricLabel: 'BALANCE:',
    subMetricValue: '-40',
    status: 'RED',
    order: 27,
  },
  {
    id: 'sfgpj',
    code: 'SFGPJ',
    name: 'PJ SFG',
    area: 'ASSY',
    metricLabel: 'OUTPUT RATE:',
    value: '94.5%',
    change: '0%',
    subMetricLabel: 'BALANCE:',
    subMetricValue: '0',
    status: 'YELLOW',
    order: 28,
  },
  {
    id: 'sj650',
    code: 'SJ650',
    name: 'ASSY SCREW JACK',
    area: 'ASSY',
    metricLabel: 'OUTPUT RATE:',
    value: '101.5%',
    change: '+0.8%',
    subMetricLabel: 'BALANCE:',
    subMetricValue: '+25',
    status: 'GREEN',
    order: 29,
  },
  {
    id: 'tw',
    code: 'TW',
    name: 'TIRE WRENCH',
    area: 'ASSY',
    metricLabel: 'OUTPUT RATE:',
    value: '89.0%',
    change: '-1.15%',
    subMetricLabel: 'BALANCE:',
    subMetricValue: '-18',
    status: 'RED',
    order: 30,
  },
  {
    id: 'ub14',
    code: 'UB14',
    name: 'UNDER BRACKET 1-4',
    area: 'MACHINING',
    metricLabel: 'OUTPUT RATE:',
    value: '97.5%',
    change: '0%',
    subMetricLabel: 'BALANCE:',
    subMetricValue: '0',
    status: 'YELLOW',
    order: 31,
  },
  {
    id: 'ub23',
    code: 'UB23',
    name: 'UNDER BRACKET 2-3',
    area: 'MACHINING',
    metricLabel: 'OUTPUT RATE:',
    value: '81.0%',
    change: '-2.85%',
    subMetricLabel: 'BALANCE:',
    subMetricValue: '-54',
    status: 'RED',
    order: 32,
  },
  {
    id: 'ub5',
    code: 'UB5',
    name: 'UNDER BRACKET 5',
    area: 'MACHINING',
    metricLabel: 'OUTPUT RATE:',
    value: '106.1%',
    change: '+0.6%',
    subMetricLabel: 'BALANCE:',
    subMetricValue: '+65',
    status: 'GREEN',
    order: 33,
  },
  {
    id: 'ub67',
    code: 'UB67',
    name: 'UNDER BRACKET 6-7',
    area: 'ASSY',
    metricLabel: 'OUTPUT RATE:',
    value: '94.0%',
    change: '0%',
    subMetricLabel: 'BALANCE:',
    subMetricValue: '0',
    status: 'YELLOW',
    order: 34,
  },
];

export const INITIAL_OVERVIEW: SystemOverviewData = {
  title: 'ANDON',
  subtitle: 'PPIC',
  dashboardName: 'Production Planning and Inventory Control',
  shift: 'Shift 2',
  overallQuality: {
    label: 'Composite',
    changePercent: '-0.05%',
    changeAbsolute: '-3.14',
    trend: 'down',
  },
  metrics: {
    totalLines: '34 LINES',
    totalProducedParts: '17,239 Pcs',
    overallAchievement: '96.4%',
  },
};
